name: Build Pygame Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4.4.0
        with:
          python-version-file: .python-version

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_strategy_games/requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          cd src/oblique_strategy_games
          pyinstaller --onefile --windowed --name oblique_games --add-data "assets;assets" main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-windows
          path: src/oblique_strategy_games/dist/oblique_games.exe

  build-mac:
    name: Build macOS Executable
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4.4.0
        with:
          python-version-file: .python-version

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_strategy_games/requirements.txt
          pip install pyinstaller

      - name: Build macOS Executable
        run: |
          cd src/oblique_strategy_games
          pyinstaller --onefile --windowed --name oblique_games --add-data "assets:assets" main.py

      - name: Upload macOS Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-mac
          path: src/oblique_strategy_games/dist/oblique_games
