name: Build Pygame Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build Windows Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "assets;assets" main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-windows
          path: src/oblique_games/dist/oblique-games.exe

  build-mac-arm64:
    name: macOS (Apple Silicon)
    runs-on: macos-14  # Ensures the runner is ARM64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build macOS ARM64 Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games-arm64 --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload macOS ARM64 Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-mac-arm64
          path: src/oblique_games/dist/oblique-games-arm64

  build-mac-x86_64:
    name: macOS (Intel)
    runs-on: macos-13  # Ensures the runner is x86_64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build macOS x86_64 Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games-x86_64 --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload macOS x86_64 Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-mac-x86_64
          path: src/oblique_games/dist/oblique-games-x86_64

  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build Linux Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-linux
          path: src/oblique_games/dist/oblique-games
