name: Build Pygame Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-13, macos-14, ubuntu-latest]
        theme: [original, aquatic]
    name: Build on ${{ matrix.os }} with theme ${{ matrix.theme }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Copy games into source
        run: |
          make copy_theme THEME=${{ matrix.theme }}

      - name: Set Executable Name
        run: echo "EXEC_NAME=oblique-${{ (matrix.theme == 'aquatic') && 'aquatic-' || '' }}games" >> $GITHUB_ENV
        shell: bash

      - name: Build Executable (Windows)
        if: runner.os == 'Windows'
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name ${{ env.EXEC_NAME }} --icon=assets/img/icon/icon_64x64.png --add-data "assets;assets" main.py
        shell: cmd

      - name: Build Executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name ${{ env.EXEC_NAME }} --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py
        shell: bash

      - name: Determine Architecture (macOS/Linux)
        if: runner.os != 'Windows'
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV
        shell: bash

      - name: Set OS Label
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest) echo "OS_LABEL=linux" >> $GITHUB_ENV ;;
            windows-latest) echo "OS_LABEL=windows" >> $GITHUB_ENV ;;
            macos-13 | macos-14) echo "OS_LABEL=macOS" >> $GITHUB_ENV ;;
            *) echo "OS_LABEL=${{ matrix.os }}" >> $GITHUB_ENV ;;
          esac
        shell: bash

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXEC_NAME }}-${{ env.OS_LABEL }}-${{ env.ARCH || 'x86_64' }}-${{ matrix.theme }}
          path: src/oblique_games/dist/${{ env.EXEC_NAME }}${{ (runner.os == 'Windows') && '.exe' || '' }}
