name: Build Pygame Executable

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        theme: [original, aquatic]
    name: Build on ${{ matrix.os }} with theme ${{ matrix.theme }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Copy games into source
        run: |
          make copy_games THEME=${{ matrix.theme }}

      - name: Build Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "$(if [ "$RUNNER_OS" == "Windows" ]; then echo 'assets;assets'; else echo 'assets:assets'; fi)" main.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-${{ matrix.os }}-${{ matrix.theme }}
          path: src/oblique_games/dist/oblique-games${{ (matrix.os == 'windows-latest') && '.exe' || '' }}
