name: Release to Itch.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Runs on any tag push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-windows
          path: build/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-mac
          path: build/mac

      - name: Deploy Windows Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/windows/oblique-games.exe
          project: ${{ secrets.ITCHIO_PROJECT }}  # Ensure this secret is set
          channel: windows
          version: ${{ github.ref_name }}  # Uses the tag name as the version
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      - name: Deploy macOS Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/mac/oblique-games
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: mac
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
