name: Build and Release to Itch.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Runs on any tag push

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build Windows Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "assets;assets" main.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-windows
          path: src/oblique_games/dist/oblique-games.exe

  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build Linux Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-linux
          path: src/oblique_games/dist/oblique-games

  build-mac-arm64:
    name: Build macOS (Apple Silicon)
    runs-on: macos-14  # Runs on Apple Silicon (arm64)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          arch -arm64 pip install -r src/oblique_games/requirements.txt
          arch -arm64 pip install pyinstaller pillow

      - name: Build macOS ARM64 Executable
        run: |
          cd src/oblique_games
          arch -arm64 pyinstaller --onefile --windowed --name oblique-games-arm64 --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload macOS ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-mac-arm64
          path: src/oblique_games/dist/oblique-games-arm64

  build-mac-x86_64:
    name: Build macOS (Intel)
    runs-on: macos-13  # Runs on Intel Macs (x86_64)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          arch -x86_64 pip install -r src/oblique_games/requirements.txt
          arch -x86_64 pip install pyinstaller pillow

      - name: Build macOS x86_64 Executable
        run: |
          cd src/oblique_games
          arch -x86_64 pyinstaller --onefile --windowed --name oblique-games-x86_64 --icon=assets/img/icon/icon_64x64.png --add-data "assets:assets" main.py

      - name: Upload macOS x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oblique_games-mac-x86_64
          path: src/oblique_games/dist/oblique-games-x86_64

  release:
    name: Release to Itch.io
    needs: [build-windows, build-linux, build-mac-arm64, build-mac-x86_64]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-windows
          path: build/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-linux
          path: build/linux

      - name: Download macOS ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-mac-arm64
          path: build/mac-arm64

      - name: Download macOS x86_64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-mac-x86_64
          path: build/mac-x86_64

      - name: Deploy Windows Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/windows/oblique-games.exe
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: windows
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      - name: Deploy Linux Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/linux/oblique-games
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: linux
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}

#      - name: Deploy macOS ARM64 Build to Itch.io
#        uses: robpc/itchio-upload-action@v1
#        with:
#          path: build/mac-arm64/oblique-games-arm64
#          project: ${{ secrets.ITCHIO_PROJECT }}
#          channel: mac
#          version: ${{ github.ref_name }}
#          api-key: ${{ secrets.ITCHIO_API_KEY }}

      - name: Deploy macOS x86_64 Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/mac-x86_64/oblique-games-x86_64
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: mac
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
