#name: Release to Itch.io
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy to Itch.io
#        uses: robpc/itchio-upload-action@v1
#        with:
#          path: src/oblique_strategy_games/web.zip
#          project: ${{ secrets.ITCHIO_PROJECT }}  # Ensure this secret is set
#          channel: html5  # e.g., 'html5', 'windows', 'linux'
#          version: ${{ github.run_number }}-${{ github.run_id }}  # Generates a unique version
#          api-key: ${{ secrets.ITCHIO_API_KEY }}
#
