name: Build and Release to Itch.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Runs on any tag push

jobs:
  build:
    name: Build Pygame Executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: oblique_games-windows
            output_file: oblique-games.exe
            channel: windows
          - os: macos-latest
            artifact_name: oblique_games-mac
            output_file: oblique-games
            channel: mac

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r src/oblique_games/requirements.txt
          pip install pyinstaller pillow

      - name: Build Executable
        run: |
          cd src/oblique_games
          pyinstaller --onefile --windowed --name oblique-games --icon=assets/img/icon/icon_64x64.png --add-data "assets${{ runner.os == 'Windows' && ';' || ':' }}assets" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: src/oblique_games/dist/${{ matrix.output_file }}

  release:
    name: Release to Itch.io
    needs: build  # Ensure build completes before releasing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-windows
          path: build/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: oblique_games-mac
          path: build/mac

      - name: Deploy Windows Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/windows/oblique-games.exe
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: windows
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      - name: Deploy macOS Build to Itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/mac/oblique-games
          project: ${{ secrets.ITCHIO_PROJECT }}
          channel: mac
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
